name: 🚀 Deploy Laravel App on Push

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      # - name: Install Dependencies
      #   run: composer install --no-dev --prefer-dist --no-scripts

      - name: 📂 Sync files to server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 162.254.39.24
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
          protocol: ftps # More secure than FTP
          passive: true # Prevents connection issues
